### ISSUE TITLE
How to use Programmatically

### ISSUE THREAD

**Issue by ghost** [phimage/CustomSegue#1]
Hello 
this is really cool to used , thanks and Really appreciated 
it is easy to use in IBInspector 
but how can i used it programmtically ?

**Comment by phimage** [comment]
I am not aware of method to use segue without storyboard

But I think you can use the `NSViewControllerPresentationAnimator` to present a view
There is `TransitionAnimator` class for instance

``` swift
parentController.presentViewController(viewController, animator: animator)
```

or with my extensions if you have already set the parent controller

``` swift
viewController.present(.animator(animator: animator)) // I think I will remove argument name ,too much animator word
```

**Comment by ghost** [comment]
> I am not aware of method to use segue without storyboard

same here , looking for here and there but no answer till now 

for instance i used 

>  self.presentViewController(sourceViewController, animator: TransitionAnimator() as NSViewControllerPresentationAnimator)

it doing sheetway but  i need slidefromleft how i can achieve this ? 

thankss

**Comment by phimage** [comment]
Customize `TransitionAnimator`

``` swift
let animator = TransitionAnimator()
animator.transition = [.slideLeft, .crossfade]
// animator.duration = ...
```

**Comment by ghost** [comment]
yeah , meanwhile i customized it

i use only slideleft  
Thank you very much :)
