### ISSUE TITLE
CustomSegue not showing up in IB module dropdown

### ISSUE THREAD

**Issue by ivanmkc** [phimage/CustomSegue#2]
Hi, 

I've built the Demo project successfully and in the Storyboard, I see that each segue has a custom class assigned to it successfully (in the attributes inspector). However, in my project I can't type it (it doesn't autocomplete) and the module dropdown below is empty as well.

I can import CustomSegue fine in a Swift file but not in the IB.

How did you get it working in the Demo project? Btw, I'm using Cocoapods. I tried Carthage but had the same issue.

Thanks for your help and for writing this much needed code.
Ivan

**Comment by phimage** [comment]
I did nothing special in example project, see my example podfile

In my experience sometimes xcode do not refresh well if it is not compiled one time
Did you see the framework compiled in your workspace? in Pods/Products/CustomSegue.framework

**Comment by ivanmkc** [comment]
Thanks, I just had to refresh I believe.
